### ISSUE TITLE
Dim all monitors

### ISSUE THREAD

**Issue by funbben** [the0neyouseek/MonitorControl#28] opened 2018-04-13 09:55 UTC
It would be nice to be able to dim all monitors when dimming one screen
(It could be set as an option)

**Comment by funbben** [comment] 2018-04-13 11:24
Well, I just noticed that there already is an option for that, however the mac built-in display doesn't dim brightness when using monitor control

**Comment by the0neyouseek** [comment] 2018-04-14 09:45
Hi @funbben,

This is a duplicate of #14 😄 
I'm closing this, If you want to further discuss this issue, please go and post a message there.

Have a nice day.

**Closed by the0neyouseek** 2018-04-14 09:45 UTC
Labels: duplicate
