### ISSUE TITLE
Two Monitors but only one works

### ISSUE THREAD

**Issue by Mibra-de** [the0neyouseek/MonitorControl#215] opened 2020-05-09 11:34 UTC
Hallo, i have two Samsung U32R592 both of them on a MacMini over Tunderbolt to Displayport. One of them are controllable the other one dosn´t work. Each monitor on its own works fine. Any ideas?

**Comment by lucguerraz** [comment] 2020-05-09 14:36
I have two Asus Monitors, same make and model. And I have this issue too. Thanks for any help

**Comment by bottlebug** [comment] 2020-05-14 04:44
I have the same issue with my 2 LG displays. Both connected via HDMI to USB-C adapters.

**Comment by JoniVR** [comment] 2020-05-14 06:53
Duplicate of #49

**Closed by JoniVR** 2020-05-14 06:53 UTC
