### ISSUE TITLE
Option to hide the menu bar icon

### ISSUE THREAD

**Issue by akshathjain** [the0neyouseek/MonitorControl#209] opened 2020-04-25 00:32 UTC
Thanks for the great app! Would it be possible to add an option to hide the menu bar icon? I only use the keyboard shortcuts, so the menu bar icon doesn't serve much purpose.

**Comment by JoniVR** [comment] 2020-05-14 06:55
duplicate of #189

**Closed by JoniVR** 2020-05-14 06:55 UTC
