### ISSUE TITLE
Display: Samsung  C27F390

### ISSUE THREAD

**Issue by SicxA1** [the0neyouseek/MonitorControl#145] opened 2019-10-20 15:06 UTC
Display: Samsung  C27F390 

Monitor Control doesn't work constant
and it only works  when contrast slider is activated 

Mojave 10.14.6/ Mac mini Server (Late 2012)2,3 GHz Intel Core i7/16 GB 1600 MHz DDR3/ Intel HD Graphics 4000 1536 MB/

**Comment by JoniVR** [comment] 2019-12-03 14:46
That is possible.. you could try some of the [advanced preferences](https://github.com/the0neyouseek/MonitorControl/wiki/Advanced-Preferences) but it usually means your dock/connector/screen doesn't properly support it.. Try a different cable or some different configurations, also try if ddcctl does work.

Closing as duplicate of #61

**Closed by JoniVR** 2019-12-03 14:46 UTC
