### ISSUE TITLE
MonitorControl doesn't work with Mac Mini 2018 at all

### ISSUE THREAD

**Issue by kikiwora** [the0neyouseek/MonitorControl#102] opened 2019-06-03 07:28 UTC
I have used this monitor (HP Z22n G2) with my previous mac mini (2012) and it worked just fine via both HDMI and DisplayPort.

However, after updating my mac to 2018 model I'm no longer able to control my display.

Version 1.5.0 didn't detect display at all, version 1.5.2 detects and shows on-screen HUD, but never actually changes brightness or contrast.

So I assume that this is an issue with Mac Mini 2018 itself. Already tested on other mini 2018 devices and got the same result (so not an issue with this device instance but with model).

Furthermore, I've tested NativeBrightness and have had the same issue there.
Maybe this issues is related to DDC/CI library or DDC/CI control is absent in this model.

**Comment by Sico93** [comment] 2019-06-12 20:15
I am also using a 2018 Mac mini, using a Dell U3818DW connected by USB-C and am able to change brightness just fine. 
Sound works somewhat strange: Mute doesn't work at all while in- or decreasing the volume works fine (until you want to shut sound off completely). So there is alway still some sound left even at the Point where macOS tells me "muted".

**Comment by kikiwora** [comment] 2019-06-14 10:50
Just in case, I use HP Z22n G2 monitors, one is connected via HDMI directly and one connected via Type-C to HDMI converter cable (good one). Neither of them I can control using this app nor another similar DDC\CI control app for macOS. But all those apps worked fine with 2012 device via same ports and the same cable (HDMI, but DisplayPort instead of Type-C).

And this is really strange - @Sico93 tells us that he's able to control his monitor, thus DDC/CI should be implemented on hardware lever of the device, so this is definitely a software issue, but probably with underlying DDC/CI control library.

**Comment by waydabber** [comment] 2019-06-15 17:37
I tested the following options:

- Mac Mini 2018 via HDMI: _**does not work**_
- Mac Mini 2018 via USB-C to HDMI adapter *: **works**
- Mac mini 2018 via USB-Type-C to DisplayPort adapter: **works**
- Mac mini 2018 via USB-Type-C (connected to a USB-C monitor *): **works**
- Mac Mini 2018 + eGPU (Radeon RX 5700) via HDMI: **works**
- Mac Mini 2018 + eGPU (Radeon RX 5700) via DisplayPort: **works**

Summary: The Intel UHD 630 via native HDMI seems to be unsupported on Mac Mini 2018.

<i>* As far as I know, USB-C adapters use _DisplayPort Alt Mode_ protocol even in case of a USB-C to HDMI adapter - the adapter converts the native DisplayPort signal to HDMI - there is no native HDMI output using USB-C.</i>

**Comment by KNNSpeed** [comment] 2019-08-29 00:55
In the same boat. A DisplayPort Alt Mode adapter works (I'm using one by Plugable), but the native HDMI port does not. The native HDMI port of a Late 2013 MacBook Pro does work with the same monitor, however.

The native HDMI on the Mac Mini has a lot of this in the log:

2019-08-28 20:48:42.636754-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:42.923244-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:43.188042-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:43.200635-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Checksum of reply does not match. Expected 128, got 110.
2019-08-28 20:48:43.444017-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:43.455937-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Checksum of reply does not match. Expected 110, got 190.
2019-08-28 20:48:43.526407-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:43.538492-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Checksum of reply does not match. Expected 190, got 128.
2019-08-28 20:48:43.647192-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:43.659912-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Checksum of reply does not match. Expected 128, got 110.
2019-08-28 20:48:43.841344-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:43.853547-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Checksum of reply does not match. Expected 110, got 190.
2019-08-28 20:48:43.932290-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:43.944935-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Checksum of reply does not match. Expected 190, got 128.
2019-08-28 20:48:44.032659-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:44.044645-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Checksum of reply does not match. Expected 128, got 110.
2019-08-28 20:48:44.201505-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:44.214090-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Checksum of reply does not match. Expected 110, got 190.
2019-08-28 20:48:44.386491-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Failed to send request to interface 0 for framebuffer with ID 50467.
2019-08-28 20:48:44.399155-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Checksum of reply does not match. Expected 190, got 128.
2019-08-28 20:48:44.399384-0400 0xdda5     Error       0x0                  1036   0    MonitorControl: (DDC) Reading 98 failed.
2019-08-28 20:48:44.592731-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Checksum of reply does not match. Expected 128, got 110.
2019-08-28 20:48:44.592851-0400 0xdda3     Error       0x0                  1036   0    MonitorControl: (DDC) Reading 16 failed.

The DisplayPort Alt Mode adapter only has occasional checksum hiccups, but nothing like the HDMI port (notice that the checksums appear to be exactly one off in the above logs). I think the native HDMI port is actually using HDMI Alt Mode since in Sound preferences it shows up as DisplayPort instead of HDMI.

**Comment by KNNSpeed** [comment] 2019-08-29 03:49
Some more data:
2019-08-28 23:33:21.842438-0400 0xaafb     Error       0x0                  935    0    MonitorControl: (DDC) Checksum of reply does not match. Expected 128, got 110.
2019-08-28 23:33:21.842649-0400 0xaafb     Debug       0x0                  935    0    MonitorControl: (DDC) Response was: 6E 80 BE 6E 80 BE 6E 80 BE 6E 80
2019-08-28 23:33:21.842690-0400 0xaafb     Error       0x0                  935    0    MonitorControl: (DDC) Reading 16 failed.

I think I see a problem here... Replydata.last! is 0x80 (128), but the checksumming algorithm in DDC.swift is computing 0x6E (110). So it looks like my 2018 Mac Mini's HDMI port is actually working, but the algorithm in DDC.swift is not. The length of the message is actually 0 bytes--the 8 in 0x80 is a feature flag, and BE is the checksum. DDC.swift's "sendmessage" function does not take this into account at all, and just computes the checksum for the entire message. This is probably also the root cause of what's showing up in #82. According to VESA spec, dummy values can be sent into a buffer, but it is the host's responsibility to make sure it is interpreting the message correctly (it's in section 6.5.1 Message Buffer Size Requirements of VESA DDC/CI spec v1.1).

**Comment by JoniVR** [comment] 2019-09-15 00:37
New release (v1.7.0) includes the updated DDC.swift framework, can someone please test it and report back if it's fixed or not?

**Comment by waydabber** [comment] 2019-09-15 08:05
Unfortunatelly native HDMI still does not work on Mac Mini 2018 using 1.7.0. :( USB-C and eGPU works fine.

Note: for whatever reason, changing brightness is a little bit choppy/laggy since 1.4.0. I always revert to JoniVR's forked version since changing brightness is super responsive and smooth with that version.

**Comment by anamba** [comment] 2019-10-21 06:08
I have a Mac Mini 2018 with a Dell U2515H. Up until now I was using HDMI to HDMI, and brightness adjustment did not work. But I just got a new USB-C to DP adapter and connected that way, it works great. (Also works fine with my 2015 13" MacBook Pro using a mini DP to DP cable, but that's not really relevant here.)

**Comment by kikiwora** [comment] 2019-10-21 06:14
Well, one USB-C to HDMI adapter (cord-like) didn't work for me on mac mini 2018, but the other one did. Have no idea why is that, cause the cheaper one actually worked, not the expensive one.
And that is weird.

**Comment by JoniVR** [comment] 2019-10-21 11:16
> Unfortunatelly native HDMI still does not work on Mac Mini 2018 using 1.7.0. :( USB-C and eGPU works fine.

It's different for every cable and connection. Some cables or adapters just don't work with ddc at all. Usually the problem is not with the software but with the cable. 

> Note: for whatever reason, changing brightness is a little bit choppy/laggy since 1.4.0. I always revert to JoniVR's forked version since changing brightness is super responsive and smooth with that version.

Yes, this will probably get resolved in #134

**Comment by JoniVR** [comment] 2019-10-21 11:18
I'm going to consider this closed as it's probably resolved and in the situations where it doesn't work it's probably due to cable/adapter. We can't possibly support all cables and adapters, so make sure you try different connectors, cables and adapters first. It's also a duplicate of #61

**Closed by JoniVR** 2019-10-21 11:18 UTC
Labels: Priority: Minor, Type: Bug

**Comment by waydabber** [comment] 2019-10-21 11:46
Well, USB-C to HDMI adapters will differ on the basis of their implementation (do they use HDMI or DisplayPort Alt mode internally), so this might make the results inconclusive. But the Mac Mini 2018 internal HDMI does not work and this is a consinstent result. I tested with the same cable, same Mac Mini 2018 through the internal HDMI port and a Thunderbolt eGPU HDMI port - the latter one works, the former one does not.

**Comment by diogoterremoto** [comment] 2020-04-14 22:22
Can confirm: brightness control of a Dell U2518D monitor via native HDMI from a Mac mini 2018 does not seem to work. I'm going blind!

**Comment by ivanhtp** [comment] 2020-05-25 20:09
Same here. I'm using a 2020 Mac Mini via HDMI and a LG Ultra HD model 32UD59-B.
MonitoControl detects my display, it shows the brightness overlay but no change on brightness at all.

Curiously I used this very same monitor on a macmini Hackintosh (i7 8700) but via DisplayPort and it worked flawlessly.

It must be the macmini.

**Comment by SheNight** [comment] 2020-06-02 20:27
I confirm, i try 3 different hdmi cable and MonitorControl or NativeDisplayBrightness doesn't work on Mac Mini 2020. Else USB-C to HDMI cable, it works fine.

I'm not sure it's a hardware problem, maybe there is a possible to fix this on software. Someone to investigate ?

Thanks!

**Comment by hyoshb** [comment] 2020-10-10 10:27
I also had this same issue, solved it this way:

**These two did not work:**
[Mac Mini 2018] - [HDMI to HDMI Cable] - [Monitor]
[Mac mini 2018] - [USB-C to HDMI Cable] - [Monitor]

**This worked perfectly for me:**
[Mac Mini 2018] - [USB-C to HDMI _**Adaptor**_] - [HDMI-to-HDMI Cable] - [Monitor]

_Condition: USB-C to HDMI adaptor must support something called **DP Alt Mode**_

**Comment by askedrelic** [comment] 2020-12-21 22:36
Thanks for this thread, it helped fix my similar problem while testing this program and https://github.com/kfix/ddcctl
I have a 2018 MacMini - HDMI - Monitor connection that wasn't working. A different DisplayPort connection with a MacBookPro worked fine.

Using a USBC-HDMI adapter fixed it (this adapter https://www.amazon.com/Anker-Aluminum-Pixelbook-Compatible-Thunderbolt/dp/B07THJGZ9Z/)

**Comment by casi7el** [comment] 2021-11-29 09:08
> I also had this same issue, solved it this way:
> 
> **These two did not work:** [Mac Mini 2018] - [HDMI to HDMI Cable] - [Monitor] [Mac mini 2018] - [USB-C to HDMI Cable] - [Monitor]
> 
> **This worked perfectly for me:** [Mac Mini 2018] - [USB-C to HDMI _**Adaptor**_] - [HDMI-to-HDMI Cable] - [Monitor]
> 
> _Condition: USB-C to HDMI adaptor must support something called **DP Alt Mode**_


Could u give me info what exactly brand of “usb-c to hdmi adaptor”?
I’m using ugreen usb c to hdmi 4k60fps adaptor, but it doesn’t work
