### ISSUE TITLE
Not working with Hub/Dock

### ISSUE THREAD

**Issue by jellybeaner101** [the0neyouseek/MonitorControl#153] opened 2019-11-23 08:47 UTC
First off let me say a big thank you to the dev/s of MonitorControl for a great piece of software and been working great since I started using it last year !

I recently bought a Thunderbolt hub with a DisplayPort output port. I could be wrong but MonitorControl doesn't seem to like this setup.

**Comment by JoniVR** [comment] 2019-12-03 14:43
That is possible.. you could try some of the [advanced preferences](https://github.com/the0neyouseek/MonitorControl/wiki/Advanced-Preferences) but it usually means your dock/connector/screen doesn't properly support it..

Closing as duplicate of #61

**Closed by JoniVR** 2019-12-03 14:43 UTC
