### ISSUE TITLE
LG 27UK850 control works only via USB-C

### ISSUE THREAD

**Issue by gaevoc** [the0neyouseek/MonitorControl#156] opened 2019-12-03 12:45 UTC
Hi,
thank you for such a nice utility!
MonitorControl works nicely on my LG 27UK850 when connected to a Mac mini 2018 via USB-C but id seems not to work via HDMI, is it correct?

Thank you in advance
Gaetano

**Comment by JoniVR** [comment] 2019-12-03 14:44
That is possible.. you could try some of the [advanced preferences](https://github.com/the0neyouseek/MonitorControl/wiki/Advanced-Preferences) but it usually means your dock/connector/screen doesn't properly support it.. Best option imo would be to try and switch to USB-C. 

Closing as duplicate of #61

**Closed by JoniVR** 2019-12-03 14:44 UTC

**Comment by gaevoc** [comment] 2019-12-03 15:35
> That is possible.. you could try some of the [advanced preferences](https://github.com/the0neyouseek/MonitorControl/wiki/Advanced-Preferences) but it usually means your dock/connector/screen doesn't properly support it.. Best option imo would be to try and switch to USB-C.
> 
> Closing as duplicate of #61

Thanks, I will try to tweak a little with the preferences
