### ISSUE TITLE
freezed my hackitosh right from the start. Restart required to get back.

### ISSUE THREAD

**Issue by lazyevgen** [the0neyouseek/MonitorControl#105] opened 2019-06-12 05:47 UTC
Sup. Was trying to play with your app for my dual monitor and my hackintosh. But it's just constantly freezing my mac. Mouse or keyboard... everything is dead. Hope u can fix it. Can send to you any info about soft or gard or any log u might need.

**Comment by JoniVR** [comment] 2019-06-13 06:43
It might help if you could share some specifications and clear explanation of what is happening exactly. Just saying it doesn't work doesn't provide us any useful info at all. 

Always provide as much info as you have on an issue right from the start if you want people to try to help you. 

You said your system freezes completely? What device, GPU, cable, display, macos version,... are you using? 

It would also help if you could install a tool like [ddcctl](https://github.com/kfix/ddcctl) and provide the output here. 
Test the following 2 ddcctl versions and post the output here if you can:

* [current master branch](https://github.com/kfix/ddcctl)
* [3d38860](https://github.com/kfix/ddcctl/tree/3d38860d5b1de15199a42d9c5a34756738ca9b2a)

If the problem is related to the `minReplyDelay` being too high, one of these versions may work and one may not, so make sure to test both.

**Comment by kikiwora** [comment] 2019-06-14 10:44
I suppose that your Hackintosh is not set up correctly. I have no such issue with my setup, and it was configured as per RehabMan`s guide. It looks like you have a GPU configuration issue, as for me.
Recommend to use **whatevergreen.kext** (Note a setup instruction - as far as I remember, you should avoid any GPU related patches when using this kext, but it works reliably almost for every card).

**Comment by stereonom** [comment] 2019-07-09 05:51
I have the current Macbook Pro (13", 2019) with the Intel Iris Plus 665 running Mac OS 10.14.5.
My monitor is the LG 38UC99-W.

When the monitor is attached via USB-C and I start the app, the mac freezes. No mouse, no keyboard.
Is there any info I can give to you, that might help fix that?

**Comment by kaydollt** [comment] 2019-07-09 06:35
Same here.. no Hackintosh

![Screen Shot on 2019-07-09 at 08:35:11](https://user-images.githubusercontent.com/968846/60864649-7e1f1780-a224-11e9-8484-c9b94f0ac9bf.png)

**Comment by inf0dr0id** [comment] 2019-07-09 15:08
I have the same problem with a 15" Late 2013 MacBook Pro and a LG 38UC99-W. Immediately after starting the app the whole system freezes, including mouse and keyboard.

![Bildschirmfoto 2019-07-09 um 17 01 57](https://user-images.githubusercontent.com/24397146/60899973-b7c74100-a26b-11e9-81c8-e3ec6f555c96.png)

**Comment by JoniVR** [comment] 2019-07-09 17:50
I'm pretty sure this is due to the `.longerDelay` value in the whitelist, because both of these displays are LG 38UC99-W and a longer delay can (and does for me) cause a system lockup.

```swift
static let whitelist: [UInt32: [UInt32: [WhitelistReason]]] = [
    7789: [
      30460: [.hideOsd, .longerDelay], // LG 38UC99-W over DisplayPort
      30459: [.hideOsd, .longerDelay], // LG 38UC99-W over HDMI
    ],
  ]
```

I run into the same issue whenever I use `.longerDelay` for my system.
Maybe we should just get rid of the whitelist and use the advanced prefs panel for these options? Since no two systems seem to be alike? @the0neyouseek @reitermarkus 

I've already started working on adding this button to the advanced prefs panel in #97, which would also make debugging a bit easier. I'm planning on adding a modal alert when changing the value and disabling automatic start when changing the setting as to prevent an infinite loop of system lockups when people change this setting.

![Screenshot 2019-07-09 at 19 47 42](https://user-images.githubusercontent.com/7591717/60911015-7beba600-a282-11e9-90e5-ee521dcd2f50.png)

**Comment by mirgut** [comment] 2019-07-25 08:59
are there any news?

**Comment by JoniVR** [comment] 2019-07-25 09:48
> are there any news?

Advanced prefs panel is as good as ready on my part, I'm just waiting on a response from @the0neyouseek. I've been testing it myself and works pretty solid. I'm not seeing any performance issues once I disable polling or set it to minimal and it doesn't freeze since the short delay is used by default.

If you want to test it out, try building the project in that PR yourself for now :)

**Comment by the0neyouseek** [comment] 2019-07-25 09:51
@mirgut @JoniVR Sorry, I’m currently on vacation right now and will back late next week. I’ll take a look then

**Comment by JoniVR** [comment] 2019-07-25 10:00
Alright, enjoy your vacation!

**Comment by mirgut** [comment] 2019-08-27 07:03
@the0neyouseek 
hope you had a great vacation.
is there any change to get the issue fixed?

thanks in advance!

**Comment by the0neyouseek** [comment] 2019-08-27 07:35
Hi @mirgut, I've just had a look at @JoniVR's PR, can you build the app and test if it fixes your issue ?

**Comment by mirgut** [comment] 2019-09-03 09:39
> 
> 
> Hi @mirgut, I've just had a look at @JoniVR's PR, can you build the app and test if it fixes your issue ?

i am not familiar with building the app. Can you help me and get me a built app?

**Comment by JoniVR** [comment] 2019-09-15 00:36
Can one of you guys please test the new release (v1.7.0) and report back if it's fixed? Should be fixed now without changing any settings.

**Comment by mirgut** [comment] 2019-09-15 09:09
for me its working fine, also in split mode. :)
THANKS A LOT

**Comment by Perkka2** [comment] 2019-10-14 14:35
My issue is with version 1.7.0, using Displayport cable (minidisplayport)
using mojave 10.14.6

As told in the other issue it's only mouse and keyboard that stops working and not the computer that freezes. mouse and keyboard control comes back when unplugging the monitor or killing the application.

It also freezes using ddcctl when querying the monitor

**Comment by JoniVR** [comment] 2020-01-24 10:33
@Perkka2 or anyone else, if you are still having freeze issues, please report your monitor/cable/gpu in #82 I'm going to consider this closed for now as most of the issues (especially surrounding the `LG 38UC99-W` should be fixed.

**Closed by JoniVR** 2020-01-24 10:33 UTC
Labels: Priority: Minor, Status: In progress, Type: Bug
