### ISSUE TITLE
Brightness Only Changes on one of two Identical Monitors

### ISSUE THREAD

**Issue by glumb** [the0neyouseek/MonitorControl#225] opened 2020-05-19 06:21 UTC
I have two Z24iG2 and one Z27 connected to my Mac. The brightness however only changes on one (every time the same) of the Z24iG2. The onscreen brightness control is shown on the  correct monitor though.

<img width="244" alt="image" src="https://user-images.githubusercontent.com/3062564/82291601-94037a00-99a9-11ea-985a-5d4ddbdeae1e.png">

<img width="789" alt="image" src="https://user-images.githubusercontent.com/3062564/82291794-ecd31280-99a9-11ea-9cb5-ef5e30423069.png">

The not changing monitor is connected via a thunderbolt dock -> display Port. Maybe that's the issue here.

**Comment by JoniVR** [comment] 2020-05-19 12:01
Duplicate of #49

**Closed by JoniVR** 2020-05-19 12:01 UTC
