### ISSUE TITLE
Brightness Only works on 1 monitor 

### ISSUE THREAD

**Issue by davidewen** [the0neyouseek/MonitorControl#204] opened 2020-04-19 20:04 UTC
Brightness Only works on 1 monitor (the primary one) under all circumstances and settings.

![image](https://user-images.githubusercontent.com/41236505/79698449-d2d4d180-823d-11ea-8b6e-ccc9183581cd.png)

![image](https://user-images.githubusercontent.com/41236505/79698460-e1bb8400-823d-11ea-8b1a-4640842536e4.png)

![image](https://user-images.githubusercontent.com/41236505/79698503-3d860d00-823e-11ea-9419-fe5c224e0e55.png)

**Comment by r1sim** [comment] 2020-04-20 19:22
This is probably a duplicate of https://github.com/the0neyouseek/MonitorControl/issues/49

**Comment by davidewen** [comment] 2020-04-20 19:45
Sounds like the same issue.

Is there any resolution? From the link you provided to #49, I don’t see that it’s been fixed.

David

**Comment by r1sim** [comment] 2020-04-20 20:01
Unfortunately there is currently no solution. This isn't really an issue of MonitorControl. It seems to be an issue of the library that handles the DDC stuff.
I ended up using https://github.com/fnesveda/ExternalDisplayBrightness. That app has a workaround for this issue. It still [isn't working on all setups](https://github.com/fnesveda/ExternalDisplayBrightness/issues/9) but maybe you are lucky and it works for you.

**Closed** 2020-04-23 07:36 UTC
Labels: Type: Duplicate
