### ISSUE TITLE
Add ability to turn off the monitor

### ISSUE THREAD

**Issue by harveyhonorg** [the0neyouseek/MonitorControl#203] opened 2020-04-19 13:00 UTC
版本号 1.6.0  
显示器型号 LG  使用机型 18款 Mac mini ，希望可以增加使用快捷键关闭显示器。

**Comment by JoniVR** [comment] 2020-04-23 07:30
I don't really speak chinese but I auto translated. If I understand correctly, you want to be able to turn the monitor off? If that's the case, this is a duplicate of #194

**Closed by JoniVR** 2020-04-23 07:30 UTC
