### ISSUE TITLE
Volume control by output device.

### ISSUE THREAD

**Issue by Vxider** [the0neyouseek/MonitorControl#186] opened 2020-03-09 07:28 UTC
`MonitorControl` now control brightness and volume by active monitor. This logic is fine for brightness because it doesn’t  know which monitor we want to control. But for volume, there is **only one** output device, it would be better if we can get the system output device and control that device no matter which monitor is activated.

For example, my main monitor is the macbook's built-in monitor, and the output device is `LG Ultra HD` (external display). The normal logic is that when I use the built-in display, I can adjust the volume of the external display by pressing the volume shortcut.

**Comment by JoniVR** [comment] 2020-03-10 20:54
duplicate of #172

**Closed by JoniVR** 2020-03-10 20:54 UTC
