### ISSUE TITLE
Request: allow volume keys to control bluetooth volume

### ISSUE THREAD

**Issue by kevinjohncutler** [the0neyouseek/MonitorControl#178] opened 2020-02-15 06:51 UTC
It would be great if MonitorControl could detect when audio is being played via bluetooth instead of the monitor and allow the default control of that device's audio with the volume keys.

**Comment by JoniVR** [comment] 2020-02-15 11:09
This issue seems to be a duplicate of #172. As I mentioned over there this is currently already the case but you may be experiencing a bug. I suggest you follow the same steps I suggested there.

**Closed** 2020-02-15 11:09 UTC
Labels: Type: Duplicate
