### ISSUE TITLE
Only able to control 1 of 2 screens

### ISSUE THREAD

**Issue by ndnathan** [the0neyouseek/MonitorControl#229] opened 2020-05-31 12:25 UTC
I have two identical BenQ BL2480 238 LED Monitors with built-in speakers / DDC connected to my 2019 13" MacBook Pro with Touch Bar (macOS Catalina 10.15.5) via USB-C to DisplayPort.

I installed the *.dmg as instructed and noticed each displays listed on the dropdown in the Menu Bar. However, both devices control the left screen's brightness and audio each way. I selected the option to 'Change Brightness/Volume for all screens' and tried actively using the other screen when selecting the option to adjust the settings.

Is there something that I am doing incorrectly? My first thought is that there might be an issue using two identical monitors. Thanks in advance for your support and consideration. I really appreciate your commitment to this project and look forward to resolving this issue soon.

**Comment by JoniVR** [comment] 2020-05-31 12:27
duplicate of #6

**Closed by JoniVR** 2020-05-31 12:27 UTC
