### ISSUE TITLE
Volume Controls: Not Working DELL U2719D

### ISSUE THREAD

**Issue by r3ppy** [the0neyouseek/MonitorControl#164] opened 2019-12-27 22:43 UTC
Hello,

My Dell Monitor U2719 seems to work fine with brightness controls, but the volume controls do not work at all. Any idea how to resolve this issue?

**Comment by JoniVR** [comment] 2020-01-09 11:39
Closing this as it seems to be a duplicate of #110.

**Closed by JoniVR** 2020-01-09 11:39 UTC
Labels: Type: Duplicate
