### ISSUE TITLE
Brightness control only adjust one of two identical monitors

### ISSUE THREAD

**Issue by karafso** [the0neyouseek/MonitorControl#166] opened 2019-12-31 07:55 UTC
I have two identical external monitors connected to my MacBook (Iiyama PL2488H). MonitorControl works fine when just one is plugged in, regardless of which port they are hooked up to. However, when both are connected, MonitorControl can only change brightness on one monitor. The second monitor does show up in the menu, but moving its slider changes the brightness on the first monitor.

![image](https://user-images.githubusercontent.com/1497462/71614340-57c2af00-2bab-11ea-8ea2-021fb0daa595.png)

**Comment by topmankong** [comment] 2019-12-31 16:13
I have the same problems, 2 DELL monitors

**Comment by JoniVR** [comment] 2020-01-09 11:50
This is a duplicate of #49, it's a long standing issue related that happens when you have 2 identical monitors.

**Closed by JoniVR** 2020-01-09 11:50 UTC
