### ISSUE TITLE
Doesn't detect screen focus in fullscreen apps

### ISSUE THREAD

**Issue by sn0wyfall** [the0neyouseek/MonitorControl#190] opened 2020-03-27 23:57 UTC
Hey! 

I just want to say firstly, this is a great app.

So the issue I'm having is that when I'm on a full screen app on my external monitor and I change brightness, it changes the brightness of my internal display. In order for it to recognize that the focus is on the monitor I need to switch to a different desktop on the monitor that doesn't contain a fullscreen app. 

Thank you for listening!

**Comment by JoniVR** [comment] 2020-04-03 12:01
Can you test this on the new v2.0.0? I think it should work now?

**Comment by cpcallen** [comment] 2020-04-25 00:03
I can confirm that this happens on 2.0.0 (Build 640).

**Comment by sn0wyfall** [comment] 2020-05-10 20:32
@JoniVR Yeah still seems to happen on 2.0.0

**Comment by oakif** [comment] 2020-05-30 01:51
@JoniVR Hey! Do you have any thoughts on this by any chance?

**Comment by JoniVR** [comment] 2020-05-31 13:05
Just noticed this is probably a duplicate of #30, so will continue tracking in there.

@oakif I haven't had the time to look into this yet and there's some higher priority stuff I want to get done first, but anyone is free to take a look at it 🙂

**Closed by JoniVR** 2020-05-31 13:05 UTC
